FROM python:3.6
WORKDIR /app
COPY . /app
RUN cd app/data && mkdir -p boiling_plan && mkdir -p schedule && mkdir -p schedule_plan && mkdir -p sku_plan && mkdir -p stats && mkdir -p templates && mkdir -p tmp
RUN sed -i -e 's/5000/8000/g' manage.py
ENV PYTHONPATH "${PYTHONPATH}:/utils/python-utils-ak"
SHELL ["/bin/bash", "-c"]
RUN mkdir /utils && cd /utils && git clone https://github.com/akadaner/python-utils-ak.git
RUN pip install -r requirements.txt
EXPOSE 8000
ENTRYPOINT ["python", "manage.py", "runserver"]
