version: '3.3'

services:
  umalat:
    build: .
    command: python /app/runserver.py runserver
    volumes:
      - .:/app
      - /root/home/data/umalat/schedule:/app/app/data/schedule_plan
      - /root/home/data/umalat/boiling_plan_schedule:/app/app/data/boiling_plan
    ports:
      - 5000:5000 
