version: '3.3'

services:
  umalat:
    build: .
    command: python -u /app/runserver.py
    restart: always
    volumes:
      - .:/app
      - /root/home/data/umalat:/app/app/data/dynamic
    ports:
      - 5000:5000
    depends_on:
      - redis
  worker:
    build: .
    command: python -u /app/manage.py run_worker
    volumes:
      - .:/app
      - /root/home/data/umalat:/app/app/data/dynamic
    restart: always
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:6-alpine

