version: '3.3'

services:
  umalat:
    build: .
    command: python /app/runserver.py runserver
    volumes:
      - .:/app
      - /root/home/data/umalat:/app/app/data/dynamic
    ports:
      - 5000:5000
