version: '3.3'

services:
  umalat:
    build: .
    command: python -u /umalat/runserver.py
    restart: always
    volumes:
      - .:/umalat
      - /root/home/data/umalat:/umalat/app/data/dynamic
    ports:
      - 5000:5000
    depends_on:
      - redis
  worker:
    build: .
    command: bash -c "env FLASK_APP=manage.py python -m flask run_worker"
#    command: python -u -m flask run_worker
    volumes:
      - .:/umalat
      - /root/home/data/umalat:/umalat/app/data/dynamic
    restart: always
    environment:
      FLASK_APP: "manage.py"
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:6-alpine

