"""empty message

Revision ID: 36187b3114be
Revises: 0ee8af7446b3
Create Date: 2020-10-25 18:43:39.116895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36187b3114be'
down_revision = '0ee8af7446b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termizators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('termizators', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
