"""empty message

Revision ID: 3931fa39575d
Revises: 5e5db68cbaa7
Create Date: 2020-12-10 08:31:16.647956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3931fa39575d'
down_revision = '5e5db68cbaa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boiling_form_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sku_boiling_form_factor',
    sa.Column('bff_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bff_id'], ['boiling_form_factors.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('bff_id', 'sku_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku_boiling_form_factor')
    op.drop_table('boiling_form_factors')
    # ### end Alembic commands ###
