"""empty message

Revision ID: 3d9cfe9a02f4
Revises: 6eb0b4a33ea0
Create Date: 2020-10-23 16:59:54.166901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9cfe9a02f4'
down_revision = '6eb0b4a33ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packings', sa.Column('name', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packings', 'name')
    # ### end Alembic commands ###
