"""empty message

Revision ID: 47fc7ff7a476
Revises: 3931fa39575d
Create Date: 2020-12-14 22:19:11.192399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fc7ff7a476'
down_revision = '3931fa39575d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('boiling_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boiling_id'], ['boilings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheese_types')
    # ### end Alembic commands ###
