"""empty message

Revision ID: 5e5db68cbaa7
Revises: 27cd21ea1d83
Create Date: 2020-12-07 19:07:24.119092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5db68cbaa7'
down_revision = '27cd21ea1d83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boilings', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boilings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
