"""empty message

Revision ID: 691c57cf5004
Revises: a504889c3922
Create Date: 2021-01-10 10:10:11.620541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691c57cf5004'
down_revision = 'a504889c3922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boiling_form_factors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_cooling_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salting_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_cooling_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boiling_form_factors', schema=None) as batch_op:
        batch_op.drop_column('second_cooling_time')
        batch_op.drop_column('salting_time')
        batch_op.drop_column('first_cooling_time')

    # ### end Alembic commands ###
