"""empty message

Revision ID: 7101de049c57
Revises: b013c61426ed
Create Date: 2020-10-12 18:23:39.058827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7101de049c57'
down_revision = 'b013c61426ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('packing_reconfiguration', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('shelf_life', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'shelf_life')
    op.drop_column('skus', 'packing_reconfiguration')
    # ### end Alembic commands ###
