"""empty message

Revision ID: b013c61426ed
Revises: eb39c053c7c7
Create Date: 2020-10-12 17:32:30.528144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b013c61426ed'
down_revision = 'eb39c053c7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packings')
    op.add_column('skus', sa.Column('speed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'speed')
    op.create_table('packings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku_id', sa.INTEGER(), nullable=True),
    sa.Column('speed', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
