"""empty message

Revision ID: d45e92d8c312
Revises: 
Create Date: 2020-05-11 18:37:44.242158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45e92d8c312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese_makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_maker_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_name', sa.String(), nullable=True),
    sa.Column('leaven_time', sa.Integer(), nullable=True),
    sa.Column('solidification_time', sa.Integer(), nullable=True),
    sa.Column('cutting_time', sa.Integer(), nullable=True),
    sa.Column('draining_time', sa.Integer(), nullable=True),
    sa.Column('cheese_maker_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cheese_maker_id'], ['cheese_makers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cheese')
    op.drop_table('statuses')
    op.drop_table('cheese_makers')
    # ### end Alembic commands ###
