"""empty message

Revision ID: eb39c053c7c7
Revises: fefb76beca44
Create Date: 2020-10-12 12:37:32.274714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb39c053c7c7'
down_revision = 'fefb76beca44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pourings', sa.Column('extra_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pourings', 'extra_time')
    # ### end Alembic commands ###
