"""empty message

Revision ID: eb451cb1e26e
Revises: 44aa46806538
Create Date: 2020-12-07 12:18:13.275961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb451cb1e26e'
down_revision = '44aa46806538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_factor_short', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skus', schema=None) as batch_op:
        batch_op.drop_column('form_factor_short')

    # ### end Alembic commands ###
