"""empty message

Revision ID: f928d30ee0fe
Revises: 
Create Date: 2020-10-10 20:06:09.565856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f928d30ee0fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boilings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_lactose', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheesemakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cheese_maker_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_pouring_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pouring_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termizators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_cleaning_time', sa.Integer(), nullable=True),
    sa.Column('long_cleaning_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meltings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serving_time', sa.Integer(), nullable=True),
    sa.Column('melting_time', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('first_cooling_time', sa.Integer(), nullable=True),
    sa.Column('second_cooling_time', sa.Integer(), nullable=True),
    sa.Column('salting_time', sa.Integer(), nullable=True),
    sa.Column('boiling_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boiling_id'], ['boilings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pourings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pouring_time', sa.Integer(), nullable=True),
    sa.Column('soldification_time', sa.Integer(), nullable=True),
    sa.Column('cutting_time', sa.Integer(), nullable=True),
    sa.Column('pouring_off_time', sa.Integer(), nullable=True),
    sa.Column('boiling_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boiling_id'], ['boilings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('boiling_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boiling_id'], ['boilings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packings')
    op.drop_table('skus')
    op.drop_table('pourings')
    op.drop_table('meltings')
    op.drop_table('termizators')
    op.drop_table('statuses')
    op.drop_table('global_pouring_processes')
    op.drop_table('cheesemakers')
    op.drop_table('boilings')
    # ### end Alembic commands ###
